// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_iz3yB5OM8HkDTqjqY8MGzQppkJ3sQBA',
    appId: '1:789631569922:web:6f5dad7e1d9ffee5f2d71b',
    messagingSenderId: '789631569922',
    projectId: 'sports-app-4e722',
    authDomain: 'sports-app-4e722.firebaseapp.com',
    databaseURL: 'https://sports-app-4e722-default-rtdb.firebaseio.com',
    storageBucket: 'sports-app-4e722.appspot.com',
    measurementId: 'G-2DTJS5487J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVm_Va9qsxDzwnCZ_odKMqKT1gaVsu-YA',
    appId: '1:789631569922:android:8433a05c5f270ac1f2d71b',
    messagingSenderId: '789631569922',
    projectId: 'sports-app-4e722',
    databaseURL: 'https://sports-app-4e722-default-rtdb.firebaseio.com',
    storageBucket: 'sports-app-4e722.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhyfvjY4zp1uplF9glgCHiOWI6errPW_U',
    appId: '1:789631569922:ios:4e1db923e75692e4f2d71b',
    messagingSenderId: '789631569922',
    projectId: 'sports-app-4e722',
    databaseURL: 'https://sports-app-4e722-default-rtdb.firebaseio.com',
    storageBucket: 'sports-app-4e722.appspot.com',
    iosBundleId: 'com.example.sportsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhyfvjY4zp1uplF9glgCHiOWI6errPW_U',
    appId: '1:789631569922:ios:4e1db923e75692e4f2d71b',
    messagingSenderId: '789631569922',
    projectId: 'sports-app-4e722',
    databaseURL: 'https://sports-app-4e722-default-rtdb.firebaseio.com',
    storageBucket: 'sports-app-4e722.appspot.com',
    iosBundleId: 'com.example.sportsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_iz3yB5OM8HkDTqjqY8MGzQppkJ3sQBA',
    appId: '1:789631569922:web:68b44e1ea882342ef2d71b',
    messagingSenderId: '789631569922',
    projectId: 'sports-app-4e722',
    authDomain: 'sports-app-4e722.firebaseapp.com',
    databaseURL: 'https://sports-app-4e722-default-rtdb.firebaseio.com',
    storageBucket: 'sports-app-4e722.appspot.com',
    measurementId: 'G-XMKZ73DY4W',
  );

}